// User
export const CREATE_NEW_USER = "CREATE_NEW_USER";
export const LOGIN_USER = "LOGIN_USER";
export const GET_CURRENT_USER = "GET_CURRENT_USER";
export const FOREGT_PASSWORD = "FOREGT_PASSWORD";
export const VERIFY_RESET_CODE = "VERIFY_RESET_CODE";
export const RESET_PASSWORD = "RESET_PASSWORD";
